### ISSUE TITLE
Ask for help？

### ISSUE THREAD

**Issue by MRLEE123456** [stuartly/aflpro#1]
Hello, in your paper, the open source code TAFL for Energy Distribution Matters in Greybox Fuzzing is not available at https://github.com/stuartly/RegionFuzz.

**Comment by stuartly** [comment]
@MRLEE123456  I appreciate your attention very much！We are keeping improving the tool and will release it when it is mature.

**Comment by bloodycoder** [comment]
Hello , https://github.com/stuartly/RegionFuzz is still not available

**Comment by stuartly** [comment]
> Hello , https://github.com/stuartly/RegionFuzz is still not available

Since this software has already entered into commercial cooperation with some companies, it is not convenient to make it public. I could send a copy to your email for academic use.
